/******************************************************************************
 *
 * [ PSUninitializedConnectionException.java ]
 *
 * COPYRIGHT (c) 1999 - 2006 by Percussion Software, Inc., Woburn, MA USA.
 * All rights reserved. This material contains unpublished, copyrighted
 * work including confidential and proprietary information of Percussion.
 *
 *****************************************************************************/

package com.percussion.client.proxies;

/**
 * Exception thrown when a proxy is created while the connection to server is
 * not initialized yet.
 */
public class PSUninitializedConnectionException extends RuntimeException
{
   /**
    * Autogenerated serialization id
    */
   private static final long serialVersionUID = 1823895176828979423L;

   /**
    * Default ctor. Simply invokes super class version.
    */
   public PSUninitializedConnectionException()
   {
      super();
   }

   /**
    * Ctor that takes the error message. Invokes the base class version.
    * 
    * @see Exception#Exception(java.lang.String)
    */
   public PSUninitializedConnectionException(String message)
   {
      super(message);
   }

   /**
    * Ctor taking the error message and another exception. Invokes the base
    * class version.
    * 
    * @see Exception#Exception(java.lang.String, java.lang.Throwable)
    */
   public PSUninitializedConnectionException(String message, Throwable cause)
   {
      super(message, cause);
   }

   /**
    * Ctor taking another exception. Invokes the base class version.
    * 
    * @see Exception#Exception(java.lang.Throwable)
    */
   public PSUninitializedConnectionException(Throwable cause)
   {
      super(cause);
   }

}
