/*******************************************************************************
 *
 * [ PSUnsupportedObjectTypeException.java ]
 * 
 * COPYRIGHT (c) 1999 - 2005 by Percussion Software, Inc., Woburn, MA USA.
 * All rights reserved. This material contains unpublished, copyrighted
 * work including confidential and proprietary information of Percussion.
 *
 ******************************************************************************/

package com.percussion.client.proxies;

/**
 * Exception that is thrown when an object type is not supported by a proxy.
 */
public class PSUnsupportedObjectTypeException extends Exception
{
   /**
    * Autogenerated serialization id
    */
   private static final long serialVersionUID = 341948432561745355L;

   /**
    * @see Exception#Exception()
    */
   public PSUnsupportedObjectTypeException()
   {
      super();
   }

   /**
    * @see Exception#Exception(String)
    */
   public PSUnsupportedObjectTypeException(String message)
   {
      super(message);
   }

   /**
    * @see Exception#Exception(String, Throwable)
    */
   public PSUnsupportedObjectTypeException(String message, Throwable cause)
   {
      super(message, cause);
   }

   /**
    * @see Exception#Exception(Throwable)
    */
   public PSUnsupportedObjectTypeException(Throwable cause)
   {
      super(cause);
   }

}
